services:
  actual_server:
    container_name: actual-budget
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - "8014:5006"
    volumes:
      - ./data:/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
