services:
  tugtainer:
    container_name: tugtainer
    image: quenary/tugtainer:latest
    restart: unless-stopped
    ports:
      - "8011:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/tugtainer
    dns:
      - 8.8.8.8
      - 8.8.4.4
    labels:
      homepage.group: Utili
      homepage.name: Tugtainer
      homepage.icon: tugtainer
      homepage.href: http://10.0.0.51:8011
