services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    environment:
      - DOCKER_MODS="ghcr.io/themepark-dev/theme.park:npm"
      - TP_THEME=dark
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - "./data:/data"
      - "./letsencrypt:/etc/letsencrypt"
      - "./theme/98-themepark-npm:/etc/cont-init.d/99-themepark"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: "unless-stopped"
