services:
    uptime-kuma:
        image: "louislam/uptime-kuma:2"
        container_name: uptime-kuma
        volumes:
            - "./data:/app/data"
            - "/var/run:/var/run"
        ports:
            - "8015:3001"
        restart: unless-stopped
