providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: "Homelab"
background:
  image: https://wallpapers.com/images/high/blue-4k-firewall-web-spdkbjergnyqvzcf.webp
  blur: xl
  saturate: 40
  brightness: 25
  opacity: 50
showStats: true

layout:
  Infrastruttura:
    style: column
    columns: 1
  Smart Home:
    style: column
    columns: 1
  Produttività:
    style: column
    columns: 1
  Media:
    style: column
    columns: 1
  Sviluppo:
    style: column
    columns: 1