providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: "Homelab"
background:
  image: https://wallpapers.com/images/high/blue-4k-firewall-web-spdkbjergnyqvzcf.webp
  blur: xl
  saturate: 40
  brightness: 25
  opacity: 50
showStats: true

layout:
  Infrastruttura & Gestione:
    style: column
    columns: 1
  Smart Home & Rete:
    style: column
    columns: 1
  Produttività & Gestione:
    style: column
    columns: 1
  Media & Intrattenimento:
    style: column
    columns: 1
  Sviluppo & Automazione:
    style: column
    columns: 1
